services:
  casadocodigodb:
    image: casadocodigodb-image
    build:
      context: ./db
    env_file:
      - .env
    container_name: ${CASADOCODIGO_MYSQL_CONTAINER_NAME}
    networks:
      - casadocodigo-app-network
    restart: always
    volumes:
      - casadocodigodb-vol:/var/lib/mysql
  
  casadocodigo-app:
    image: casadocodigo-app-image
    container_name: ${CASADOCODIGO_APP_CONTAINER_NAME}
    build:
      context: ./app
      args:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_DATABASE_HOST=${CASADOCODIGO_MYSQL_CONTAINER_NAME}
    networks:
      - casadocodigo-app-network
    ports:
      - 8080:8080
    depends_on:
      casadocodigodb:
        condition: service_started
    restart: always
    volumes:
      - casadocodigo-app-vol:/opt/jboss/wildfly/standalone:rw

volumes:
  casadocodigo-app-vol:
    name: casadocodigo-app-vol

  casadocodigodb-vol:
    name: casadocodigodb-vol

networks:
  casadocodigo-app-network:
    driver: bridge
    name: casadocodigo-app-network
